---
- hosts: webservers
  sudo: yes
  tasks:
  - name: copy id_rsa to host
    copy:
      src: ~/.ssh/id_rsa
      dest: ~/.ssh
      mode: '600'
  
  - name: copy id_rsa.pub to host
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: ~/.ssh

  - name: add GitHub to known_hosts
    shell: ssh-keyscan -H -t rsa github.com

  - name: clone repo
    git:
      repo: git@github.com:jefcrauwels/pipelineprototype.git
      dest: "~/pipelineprototype"
      version: master
      accept_hostkey: yes
      key_file: "~/.ssh/id_rsa"

  - name: Node.js - Get script
    get_url:
      url: "http://deb.nodesource.com/setup_8.x"
      dest: "~/nodejs.sh"

  - name: Node.js - Set execution permission to script
    file:
      path: "~/nodejs.sh"
      mode: "u+x"

  - name: Node.js - Execute installation script
    shell: "~/nodejs.sh"

  - name: Node.js - Remove installation script
    file:
      path: "~/nodejs.sh"
      state: absent

  - name: Node.js - Install Node.js
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - build-essential
      - nodejs

  - name: Install npm
    npm: 
      path: ~/pipelineprototype
  
  - name: Install nodemon
    npm:
      name: nodemon
      global: yes
  
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: Install other packages (express, ejs...)
    npm:
      path: ~/pipelineprototype
      
  - name: Restart application
    shell: |
      cd ~/pipelineprototype
      pm2 restart ecosystem.config.js
      